from datetime import datetime


def generate_report(report_path, case_data):
    content = f"""
Brain MRI Anomaly Detection Report

Case ID: {case_data.get("case_id")}
Client Case ID: {case_data.get("client_case_id") or "Not provided"}
Original Filename: {case_data.get("original_filename")}
MRI Modality: {case_data.get("modality") or "Not provided"}
Status: {case_data.get("status")}
Abnormality Score: {case_data.get("score")}
Created At: {case_data.get("created_at")}

Notes:
{case_data.get("notes") or "No notes provided."}

Result Analysis:
The uploaded brain MRI data has been processed by the current detection workflow.
The current result is generated by a placeholder model for website integration testing.
After the real model is connected, this section can be replaced by model-based analysis.

Disclaimer:
This platform is for research and demonstration purposes only and is not intended for clinical diagnosis.

Generated At:
{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
""".strip()

    with open(report_path, "w", encoding="utf-8") as file:
        file.write(content)

    return report_path